/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CourseController;
import java.util.ArrayList;
import model.Course;

/**
 *
 * @author nimsa
 */
public class CourseForm extends javax.swing.JFrame {

    
    private int selectedCourseId = 0;
    /**
     * 
     * 
     * Creates new form CourseForm
     */
    public CourseForm() {
        initComponents();
        loadAllCourses();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCourseName = new javax.swing.JTextField();
        txtDuration = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Course Name");

        jLabel2.setText("Duration");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Course Name", "Duration"
            }
        ));
        tblCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCoursesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourses);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Course Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtDuration))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

try {
            Course course = new Course();
            course.setCourseName(txtCourseName.getText());
            course.setDuration(txtDuration.getText());

            CourseController controller = new CourseController();
            boolean isSaved = controller.addCourse(course);

            if (isSaved) {
                javax.swing.JOptionPane.showMessageDialog(this, "Course Saved Successfully!");
                loadAllCourses(); // Save වුණ ගමන් Table එක අලුත් වෙනවා
                
                txtCourseName.setText("");
                txtDuration.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to save course.");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }


        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblCoursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCoursesMouseClicked
        
        // 1. ක්ලික් කරපු පේළිය අඳුරගන්නවා
        int selectedRow = tblCourses.getSelectedRow();

        // 2. Table Model එක ගන්නවා
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tblCourses.getModel();

        // 3. ID එක අරන් selectedCourseId එකට දාගන්නවා
        selectedCourseId = Integer.parseInt(dtm.getValueAt(selectedRow, 0).toString());

        // 4. Course Name සහ Duration එක Text Fields වලට දානවා
        txtCourseName.setText(dtm.getValueAt(selectedRow, 1).toString());
        txtDuration.setText(dtm.getValueAt(selectedRow, 2).toString());
        
        
    }//GEN-LAST:event_tblCoursesMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    
        try {
            if (selectedCourseId == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a course from the table first!");
                return;
            }

            Course course = new Course();
            course.setCourseId(selectedCourseId); // Update කරද්දී ID එක අනිවාර්යයි
            course.setCourseName(txtCourseName.getText());
            course.setDuration(txtDuration.getText());

            CourseController controller = new CourseController();
            boolean isUpdated = controller.updateCourse(course);

            if (isUpdated) {
                javax.swing.JOptionPane.showMessageDialog(this, "Course Updated Successfully!");
                loadAllCourses(); 
                
                txtCourseName.setText("");
                txtDuration.setText("");
                selectedCourseId = 0; 
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to update course.");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        
        
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        try {
            if (selectedCourseId == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a course from the table first!");
                return;
            }

            int option = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this course?", "Delete Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);
            
            if (option == javax.swing.JOptionPane.YES_OPTION) {
                CourseController controller = new CourseController();
                boolean isDeleted = controller.deleteCourse(selectedCourseId);

                if (isDeleted) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Course Deleted Successfully!");
                    loadAllCourses(); 
                    
                    txtCourseName.setText("");
                    txtDuration.setText("");
                    selectedCourseId = 0;
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to delete course.");
                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseForm().setVisible(true);
            }
        });
    }
    
    
    
    private void loadAllCourses() {
     try {
         CourseController controller = new CourseController();
         ArrayList<Course> courseList = controller.getAllCourses();

         javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tblCourses.getModel();
         dtm.setRowCount(0);

         for (Course course : courseList) {
             Object[] row = {course.getCourseId(), course.getCourseName(), course.getDuration()};
             dtm.addRow(row);
         }
     } catch (Exception e) {
         javax.swing.JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
     }
 }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourses;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtDuration;
    // End of variables declaration//GEN-END:variables
}
