/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.StudentController;
import java.util.ArrayList;
import model.Student;

/**
 *
 * @author nimsa
 */
public class StudentForm extends javax.swing.JFrame {

    private int selectedStudentId = 0;
    /**
     * Creates new form StudentForm
     */
    public StudentForm() {
        initComponents();
        loadAllStudents();
        setLocationRelativeTo(null);

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Age");

        jLabel3.setText("Contact");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Contact"
            }
        ));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Student Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    try {
            // 1. Text Fields වලින් දත්ත ටික ගන්නවා
            String name = txtName.getText();
            int age = Integer.parseInt(txtAge.getText()); // Age එක ඉලක්කමක් නිසා String එක int කරනවා
            String contact = txtContact.getText();

            // 2. ඒ දත්ත දාලා Student Object එකක් (අර අපි කතා කරපු පෙට්ටිය) හදනවා
            Student student = new Student();
            student.setName(name);
            student.setAge(age);
            student.setContact(contact);

            // 3. Controller එකට කතා කරලා Object එක යවනවා Save කරන්න
            StudentController controller = new StudentController();
            boolean isSaved = controller.addStudent(student);

            // 4. Save වුණාද නැද්ද කියලා බලලා පණිවිඩයක් (Message Box) පෙන්නනවා
            if (isSaved) {
                javax.swing.JOptionPane.showMessageDialog(this, "Student Saved Successfully!");
                
                loadAllStudents();
                // Save වුණාට පස්සේ Text Fields ටික ආයෙත් හිස් කරනවා
                txtName.setText("");
                txtAge.setText("");
                txtContact.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to save student.");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number for Age.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }    // TODO add your handling code here:
    
    
    
    
    
    
    
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMouseClicked
      
// 1. ක්ලික් කරපු පේළියේ (Row) අංකය ගන්නවා
        int selectedRow = tblStudents.getSelectedRow();

        // 2. Table එකේ Model එක ගන්නවා දත්ත එලියට ගන්න
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tblStudents.getModel();

        // 3. 0 වෙනි තීරුවේ (Column) තියෙන ID එක අරන් අර අපි උඩ හදපු variable එකට දාගන්නවා
        selectedStudentId = Integer.parseInt(dtm.getValueAt(selectedRow, 0).toString());

        // 4. අනිත් තීරු (1, 2, 3) වල තියෙන දත්ත අරන් Text Fields වලට දානවා
        txtName.setText(dtm.getValueAt(selectedRow, 1).toString());
        txtAge.setText(dtm.getValueAt(selectedRow, 2).toString());
        txtContact.setText(dtm.getValueAt(selectedRow, 3).toString());        
// TODO add your handling code here:
    }//GEN-LAST:event_tblStudentsMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

try {
            // 1. Table එකෙන් කෙනෙක්ව තෝරලා නැත්නම් Error එකක් දෙනවා
            if (selectedStudentId == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a student from the table first!");
                return; // මෙතනින් කෝඩ් එක නවත්තනවා
            }

            // 2. අලුත් විස්තර ටික අරගෙන Student Object එකක් හදනවා
            Student student = new Student();
            student.setStudentId(selectedStudentId); // Update එකට ID එක අනිවාර්යයි!
            student.setName(txtName.getText());
            student.setAge(Integer.parseInt(txtAge.getText()));
            student.setContact(txtContact.getText());

            // 3. Controller එකට යවලා Update කරනවා
            StudentController controller = new StudentController();
            boolean isUpdated = controller.updateStudent(student);

            // 4. Update වුණා නම් Table එක අලුත් කරලා Text Fields හිස් කරනවා
            if (isUpdated) {
                javax.swing.JOptionPane.showMessageDialog(this, "Student Updated Successfully!");
                loadAllStudents(); // අලුත් දත්ත Table එකට Load වෙනවා
                
                txtName.setText("");
                txtAge.setText("");
                txtContact.setText("");
                selectedStudentId = 0; // වැඩේ ඉවර නිසා ID එක ආයේ 0 කරනවා
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to update student.");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid number for Age.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }


        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            // 1. කෙනෙක්ව තෝරලා නැත්නම් Error එකක් දෙනවා
            if (selectedStudentId == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a student from the table first!");
                return;
            }

            // 2. මකන්න කලින් ඇත්තටම මකන්නද කියලා අහනවා (Software Engineering Standard)
            int option = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this student?", "Delete Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);
            
            // 3. Yes එබුවොත් විතරක් මකනවා
            if (option == javax.swing.JOptionPane.YES_OPTION) {
                StudentController controller = new StudentController();
                boolean isDeleted = controller.deleteStudent(selectedStudentId); // ID එක විතරයි යවන්නේ

                if (isDeleted) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Student Deleted Successfully!");
                    loadAllStudents(); // Table එක අලුත් කරනවා
                    
                    txtName.setText("");
                    txtAge.setText("");
                    txtContact.setText("");
                    selectedStudentId = 0;
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, "Failed to delete student.");
                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        
        
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentForm().setVisible(true);
            }
        });
    }

    
    
    
    
    
    
    // Table එකට දත්ත Load කරන Method එක
    private void loadAllStudents() {
        try {
            StudentController controller = new StudentController();
            ArrayList<Student> studentList = controller.getAllStudents(); // Controller එකෙන් දත්ත ඉල්ලනවා
            
            // Table එකේ Model එක අරගන්නවා (මේකෙන් තමයි Table එකට දත්ත දාන්නේ)
            javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) tblStudents.getModel();
            dtm.setRowCount(0); // Table එකේ තියෙන පරණ දත්ත මකලා හිස් කරනවා
            
            // List එකේ ඉන්න එක එක ළමයාව අරන් Table එකේ පේළි (Rows) විදියට දානවා
            for (Student student : studentList) {
                Object[] row = {student.getStudentId(), student.getName(), student.getAge(), student.getContact()};
                dtm.addRow(row);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}



